fail:
- beginLine: 4
  detector: kubelet_key_files_set
  endLine: 4
  explanation: Ensure that the --tls-cert-file and --tls-private-key-file arguments
    are set as appropriate
  file: kubelet_key_files_set/bad.yaml
  framework: kubernetes
  provider: kubernetes
  resource: bad.yaml.bad
